apiVersion: "spec.keptn.sh/0.2.3"
kind: "Shipyard"
metadata:
  name: "shipyard-delivery"
spec:
  stages:
    - name: "qa"
      deployment_strategy: "direct"
      test_strategy: "functional"
      sequences:
        - name: "delivery"
          tasks:
            - name: "deployment"
            - name: "test"

    - name: "production"
      deployment_strategy: "blue_green_service"
      sequences:
        - name: "delivery"
          triggeredOn:
            - event: "qa.delivery.finished"
          tasks:
            - name: "deployment"

