apiVersion: webhookconfig.keptn.sh/v1beta1
kind: WebhookConfig
metadata:
  name: webhook-configuration
spec:
  webhooks:
    - type: sh.keptn.event.je-deployment.triggered
      requests:
        - url: https://events.pagerduty.com/v2/enqueue
          payload: >-
            {"payload":{"summary":"My Test 5","severity":"low","source":"sh.keptn.triggered.event"},"routing_key":"92877d39e483490ac09a20101967e88e","dedup_key":"srv01","event_action":"trigger","client":"Sample Monitoring Service","client_url":"https://datadog.service.com"}
          headers:
            - name: Content-Type
              value: application/json
          method: POST
      subscriptionID: 9481a688-07e3-409e-9706-f1bdd1c9866d
      sendFinished: false
      sendStarted: false
