apiVersion: webhookconfig.keptn.sh/v1beta1
kind: WebhookConfig
metadata:
  name: webhook-configuration
spec:
  webhooks:
    - type: sh.keptn.event.je-test.triggered
      requests:
        - url: https://keptn-sp.atlassian.net/rest/api/3/events
          payload: ""
          headers:
            - name: Accept
              value: application/json
            - name: xaror79553@lodores.com
              value: "{{.env.secret_jiraapi_token}}"
          method: GET
      envFrom:
        - name: secret_jiraapi_token
          secretRef:
            name: jira-api
            key: token
      subscriptionID: f719242b-f6c9-41a1-a2f0-c59ad4b39279
      sendFinished: true
      sendStarted: true
    - type: sh.keptn.event.je-deployment.triggered
      requests:
        - url: https://keptn-sp.atlassian.net/rest/api/3/issue
          payload: >-
            {"update":{},"fields":{"summary":"Main order flow broken","parent":{"key":"PROJ-123"},"issuetype":{"id":"10000"},"components":[{"id":"10000"}],"customfield_20000":"06/Jul/19 3:25 PM","customfield_40000":{"type":"doc","version":1,"content":[{"type":"paragraph","content":[{"text":"Occurs on all orders","type":"text"}]}]},"customfield_70000":["jira-administrators","jira-software-users"],"project":{"id":"10000"},"description":{"type":"doc","version":1,"content":[{"type":"paragraph","content":[{"text":"Order entry fails when selecting supplier.","type":"text"}]}]},"reporter":{"id":"5b10a2844c20165700ede21g"},"fixVersions":[{"id":"10001"}],"customfield_10000":"09/Jun/19","priority":{"id":"20000"},"labels":["bugfix","blitz_test"],"timetracking":{"remainingEstimate":"5","originalEstimate":"10"},"customfield_30000":["10000","10002"],"customfield_80000":{"value":"red"},"security":{"id":"10000"},"environment":{"type":"doc","version":1,"content":[{"type":"paragraph","content":[{"text":"UAT","type":"text"}]}]},"versions":[{"id":"10000"}],"duedate":"2019-05-11","customfield_60000":"jira-software-users","customfield_50000":{"type":"doc","version":1,"content":[{"type":"paragraph","content":[{"text":"Could impact day-to-day work.","type":"text"}]}]},"assignee":{"id":"5b109f2e9729b51b54dc274d"}}}
          headers:
            - name: Accept
              value: application/json
            - name: Content-Type
              value: application/json
            - name: xaror79553@lodores.com
              value: "{{.env.secret_jiraapi_token}}"
          method: POST
      envFrom:
        - name: secret_jiraapi_token
          secretRef:
            name: jira-api
            key: token
      subscriptionID: 2d46d9f2-a0fb-4d09-93c9-ddab7f505c85
      sendFinished: true
      sendStarted: true
